### ISSUE TITLE
Test claims test-api.sh not found

### ISSUE THREAD

**Issue by MattDodsonEnglish** [TrueBlocks/trueblocks-core#1522]
I've probably done something wrong here, but I found a behavior I couldn't understand.

I wanted to test what would happen if I ran the tests without an Etherscan key. So I
went into the `build` directory and ran `make tests`.

It looks like there was no problem for `ethslurp` --`[64%] Built target ethslurp`--however, at the
end of the test output there was an error message:

```shell
trueblocks-core/src/../bin/test/test.sh: line 15: test-api.sh: command not found
```

I checked and the `test-api.sh` file definitely exists in my local `bin/test/`,
so I'm not sure what that's about.

Machine: Arch Linux, 5.10.14
Version: chifra GHC-TrueBlocks//0.8.3-alpha-6e57d56e9-20210211

**Comment by tjayrush** [comment]
> On Feb 11, 2021, at 7:24 PM, MattDodsonEnglish <notifications@github.com> wrote:
> 
> 
> I've probably done something wrong here, but I found a behavior I couldn't understand.
> 
> I wanted to test what would happen if I ran the tests without an Etherscan key. So I
> went into the build directory and ran make tests.
> 
> It looks like there was no problem for ethslurp --[64%] Built target ethslurp--however, at the
> end of the test output there was an error message:
> 
> trueblocks-core/src/../bin/test/test.sh: line 15: test-api.sh: command not found

There’s a mistake in the instructions. One must add both ./bin and ./bin/tests into one’s $PATH.

One thing we could do instead of asking the user to add two paths would be to:

	a) Search the existing $PATH for a path containing trueblocks/bin
	b) append that path + /test to the path in the testing scripts

Are you any good at shell scripting?

Another alternative is to make all references to anything in the ./bin/test folder explicit but that’s a bit harder.

The worst thing would be to tell the user to add two path to their PATH.

**Comment by tjayrush** [comment]
I updated the README to include the `./bin/tests` path.
