### ISSUE TITLE
Don't expose RPC provider when running `chifra serve`

### ISSUE THREAD

**Issue by cole-h** [TrueBlocks/trueblocks-core#1641]
If you run `chifra serve --port :8080` and `curl localhost:8080/status`, you should not be able to see the RPC provider. As-is, this allows people who can hit that endpoint to lift your RPC provider if it uses e.g. infura.io and use it for their own purposes.

**Comment by tjayrush** [comment]
Thanks for you suggestion.

I think I would express this a bit differently. I think the issue should say "It should be possible to hide the RPC provider if `chifra serve` is exposed to an internet audience`.

In regular operation, both the `chifra serve` and any applications running against `chifra serve` run on the same local machine. In that case, there's no need to hide the URL because the user is the same person as is running the server.

I get your point though.

Do you have any time or interest in helping make this change? It's pretty low priority given that our focus is fully local, but I'd be willing to point you to what needs to be changed if you'd like to get involved.

**Comment by tjayrush** [comment]
Assuming a lack of interest, I close this. Please re-open if you wish to add this feature.
