### ISSUE TITLE
"Could not download zip file ..."

### ISSUE THREAD

**Issue by flux627** [TrueBlocks/trueblocks-core#1651]
I'm getting lots of `Could not download zip file <finalized|blooms>/<block range>.<bin|bloom>.gz` errors while running `chifra init`. Is this normal? I'm guessing the IPFS pins are being finicky. Does chifra automatically go back and retry these failed downloads?

If I have holes in my index, if I do `chifra scrape` afterwards, will that fill it in? Will this index be inferior since I don't have a Parity server running (only Erigon)?

**Comment by tjayrush** [comment]
`chifra init` should only be downloading the bloom filters which shouldn't take much longer than ten or fifteen minutes. Are you getting errors that indicate a problem with `finalized` or just `blooms`?

I think, but I would be very interested to learn otherwise, that if you do `chifra init` more than once it will look for each bloom filter and, if not found, download it again. In other words, if the bloom is not found, it will try to get it.

Also, when we download, we download to a temporary folder and only after unzipping do we copy the resulting unzipped file to the 'real' location. In this way, we try to avoid getting a 'partial' file (the unzip should fail if the full zip file did not download).

The hope is that either each bloom is complete or it will be re-downloaded.

That's how it's supposed to work.

It would be amazingly helpful if you could do an `ls -lR` on the `unchainedindex` folder under the TrueBlocks configuration folders and paste it here. I can compare it to our 'gold' copy and let you know of any differences.

What operating system are you on?

Have you already tried to re-run `chifra init`?

What happens when you do `chifra export` or `chifra list` on an address?

**Comment by tjayrush** [comment]
At the time of this issue, I'm pretty sure the IPFS gateway was down, so my guess is that this may have been the cause. If it continues to happen, please feel free to re-open.

**Comment by flux627** [comment]
Actually, this was happening to me because I used `snap` to install `curl` via sudo, which apparently causes problems. Uninstalled using `snap` and re-installed via `apt-get`, and everything worked fine. Apologies, meant to update /close this issue earlier.

**Comment by tjayrush** [comment]
No problem. Thanks so much for coming back and letting me know.
