### ISSUE TITLE
How to request more than 10k records from a contract

### ISSUE THREAD

**Issue by cesarvspr** [TrueBlocks/trueblocks-core#1695]
Trying to request all the records from a contract. The etherscan.io solution offers a 5k records but the total is 120k+. Any API endoint or solution can go through it all?

# What I want:

Something like this ->
https://etherscan.io/exportData?type=address&a=0x80e9540c204c05be63cfe44b43302780175b60ff

# What I tried:

ethslurp, limited to 10k 
Etherscan.io (didn't find an API that provide more than 5k)
Would like a .csv if possible

**Comment by tjayrush** [comment]
First things first. Do you have your own Ethereum node?

Your access is being rate-limited by EhterScan because requesting 155,000 records from any server will get you rate-limited. No server can give every user who ask for it 155,000 records whenever they ask. The server would crash.

So, if you don't have your own Ethereum node, the chances are you're out of luck for an API query to a server.

However, there's hope!

In one mode, `chifra slurp`, TrueBlocks allows you to query EtherScan 5,000 records at a time (so as to avoid the rate limiting) and eventually it will return all 155,000 records. Try `chifra slurp <address>`. Note that this will only return regular transactions. Please see the help file for how to query token transfers, nfts, or internal transactions.

In another mode, if you're running your own node and you have an up-to-date index, you can run `chifra export <address>`. This will return all 155,000 records of any type as quickly as possible.

I am going to close this issue and ask you kindly to spend some time reading the documentation.

We're trying very hard to answer many of these questions in the documentation.

 If you would be so kind, perhaps you'll read the docs and, if you find them inadequate, create new issues to help us improve. Or even better yet -- improve the docs. Any amount of help is welcome.

Thanks.

**Comment by cesarvspr** [comment]
Thank you so much for this kind answer. I got a bit confused cuz my first contact was with the older docs. 

Now I have the correct documentation and will be looking into it. 
Thank you so much for your support and endless effort on this very useful tool.

**Comment by tjayrush** [comment]
No problem. Happy to help.
