### ISSUE TITLE
On new installs, Chifra is not working as a wrapper for the other commands

### ISSUE THREAD

**Issue by MattDodsonEnglish** [TrueBlocks/trueblocks-core#1709]
It looks like:

* the base commands are working [1], 
* `chifra` can be called as its own tool[2], 
*  `chifra` is not working as a wrapper for the base commands[3].

_see  #examples_

This is confirmed not a $PATH issue, and it has been reproduced by two users (both on Linux machines). A second user added some info:

>the chifra help message shows fine but no other modules are being found unless called directly

## Examples

[1]
```shell
$getBlocks 12345
{ "data": [
{
  "gasLimit": 5000,
  "gasUsed": 0,
  "hash": "0x767c2bfb3bdee3f78676c1285cd757bcd5d8c272cef2eb30d9733800a78c0b6d",...
}] }
```

[2]

```shell
$chifra --version
trueBlocks GHC-TrueBlocks//0.10.2-alpha-2123d0664-20210810
```

[3]

```shell
$chifra blocks 12345
sh: line 1: getBlocks: command not found
```

[3] Is pretty weird, because obviously getBlocks is found when called directly. Perhaps chifra is not looking in the right directory.

**Comment by tjayrush** [comment]
This is really weird.

@MattDodsonEnglish All of this stuff used to work, didn't it?

`chifra` doesn't look 'in a directory' -- it looks in the $PATH, so I'm a bit confused.

**Comment by bohendo** [comment]
This happened to my install too & I just discovered how to fix it:

```
$ pwd
/home/bohendo/all/Documents/github/trueblocks-core

$ ./bin/chifra blocks --help
sh: 1: getBlocks: not found

$ ./bin/getBlocks --help

  Usage:    getBlocks [-e|-U|-t|-a|-u|-n|-c|-o|-v|-h] <block> [block...]  
  Purpose:  Retrieve one or more blocks from the chain or local cache.
...
  
$ export PATH=${PATH}:$(pwd)/bin

$ ./bin/chifra blocks --help

  Usage:    chifra blocks [-e|-U|-t|-a|-u|-n|-c|-o|-v|-h] <block> [block...]  
  Purpose:  Retrieve one or more blocks from the chain or local cache.
...
```

Installation instructions said to [add `trueblocks-core/bin` to the $PATH](https://docs.trueblocks.io/docs/prologue/installing-trueblocks/#2-add-trueblocks-corebin-to-path).

Instead of doing that, I symlinked `chifra` into my ~/bin which is already in the path, which worked for the main executable but not for any of it's dependencies eg `getBlock`

**Comment by tjayrush** [comment]
First, thanks so much for helping us figure this out.

Second, I was trying to help @MattDodsonEnglish figure this out yesterday, and I was pretty convinced it was a $PATH problem, so this confirm my suspicion.

Third, this appears to work, but I don't think it's quite the right solution.

If the $PATH value were correctly set, you should be able to run not only `chifra`, but every subcommand from any folder on your computer. 

If you do:

```
cd $HOME
chifra blocks 12
```

does that work?

**Comment by MattDodsonEnglish** [comment]
I can confirm that @bohendo 's solution worked on my machine too:

> $ export PATH=${PATH}:$(pwd)/bin

Where `$(pwd)` is really `/path/to/my/trueblocks-core` .

Quoting myself:

> This is confirmed not a $PATH issue,

I should be careful about "confirming" things :-).

I still need to wrap my head around where I went wrong with the symlink / export distinction. But for now, I'm happy to say "good enough." I'm going to add this fix to the #troubleshooting section of the install. Thanks Bohendo!

I guess, for the future, a question for Jay is whether there's a way to simplify this process on the user side, e.g. auto adding the commands to `~/.local/bin` or something. Just thinking out loud---no idea whether this is an actual problem or, if it is, that that's a viable solution.

**Comment by tjayrush** [comment]
Maybe there's a mistake or confusion in the instructions. @bohendo Where exactly did you find the instruction you mention? We can try to make it more clear.

**Comment by MattDodsonEnglish** [comment]
I believe that, in my case, where I went wrong was I had in my .bashrc

 `PATH=...` 

instead of 

`export PATH=...`

The "bad way" worked on my old .bashrc somehow and I copied it blindly.

I'm not yet clear about the distinction between these two things yet, but I'm going to use this opportunity to educate myself.

**Comment by tjayrush** [comment]
The first answer here explains it. The `export` allows child processes to access the value. When `chifra` starts, it's the parent. When it starts a shell, that shell runs the PATH command, but the command is not available to child processes as the first answer here says: https://askubuntu.com/questions/833922/what-does-the-export-path-line-in-bashrc-do.

**Comment by bohendo** [comment]
> If the $PATH value were correctly set, you should be able to run not only `chifra`, but every subcommand from any folder on your computer.

Yes this works, as long as the `trueblocks-core/bin` dir is in the $PATH then all subcommands work in $HOME or anywhere else.

> Where exactly did you find the instruction you mention? We can try to make it more clear.

https://docs.trueblocks.io/docs/prologue/installing-trueblocks/#2-add-trueblocks-corebin-to-path

These instructions are actually pretty clear in my opinion. I just made the incorrect assumption that sub-commands would look for the sub-executables relative to the parent `chifra` executable (eg checking something like `dirname $(which chifra)`) rather than searching the PATH directly.

Maybe one extra sentence that disqualifies the bad assumption I made could help other people avoid this problem.. But the docs already say "chifra only works if its underlying tools are found in your $PATH" so idk how much more clear you could make it.

> I guess, for the future, a question for Jay is whether there's a way to simplify this process on the user side, e.g. auto adding the commands to ~/.local/bin or something. Just thinking out loud---no idea whether this is an actual problem or, if it is, that that's a viable solution.

I will say, the sub-executables have very generic names and therefore have significant collision potential eg it's possible that `getLogs` would overwrite and/or get overwritten by other utilities the user has installed or by user-defined executables (unlike the base `chifra` cmd which has a nice unique name & is therefore unlikely to collide w other tools).

If there's any way to keep sub-executables out of the global executable namespace that'd be a nice improvement IMO.  Especially if it'd let us just add the one `chifra` cmd to our PATH, then this issue would be impossible to encounter again.

> The export allows child processes to access the value.

Ahh I'd always been a little hazy on when we need `export` & when not, thanks for clarifying.

**Comment by tjayrush** [comment]
> These instructions are actually pretty clear in my opinion. I just made the incorrect assumption that sub-commands would look for the sub-executables relative to the parent chifra executable (eg checking something like dirname $(which chifra)) rather than searching the PATH directly.

This is a nice idea. 

> I will say, the sub-executables have very generic names and therefore have significant collision potential eg it's possible that getLogs would overwrite and/or get overwritten by other utilities the user has installed or by user-defined executables (unlike the base chifra cmd which has a nice unique name & is therefore unlikely to collide w other tools).

This is also a very good point. I've created this issue to track. https://github.com/TrueBlocks/trueblocks-core/issues/1726
