### ISSUE TITLE
chifra export and blocks commands return different transaction timestamps for the same transaction from Rinkeby

### ISSUE THREAD

**Issue by davidfsol5** [TrueBlocks/trueblocks-core#1713]
From Rinkeby:
$ chifra blocks --fmt json 9137164
$ chifra export --fmt json 0x00a14a1d6af3e2944a3e102cf182c784f2331ffd

Tx Index 7 in blockNumber 9137164 is from 0x00a14a1d6af3e2944a3e102cf182c784f2331ffd. 

The export command lists {..., "timestamp": 1576872229, ...} or 2019-12-20T20:03:49.
The blocks command lists (..., "timestamp": 1629298156, ...} or 2021-08-18T14:49:16.

Full export tx:
{
  "hash": "0x2fe35e3cec7ee5bba3b1610ccfc8945f684f0fee2915e28deacead39ebb214fb",
  "blockHash": "0x95655a6b802bdc1dd34e4b143e7df48ea789e51242c3efeefca69eaae7193c62",
  "blockNumber": 9137164,
  "transactionIndex": 7,
  "timestamp": 1576872229,
  "from": "0x00a14a1d6af3e2944a3e102cf182c784f2331ffd",
  "to": "0xd7bb0f9d05766c0149c1a3be14c634310c4b7719",
  "value": 0,
  "gas": 60005,
  "gasPrice": 1178474583,
  "isError": 0,
  "hasToken": 1,
  "receipt": {
    "contractAddress": "0x0",
    "gasUsed": 46158,
    "effectiveGasPrice": 1178474583,
    "logs": [
      {
        "address": "0xd7bb0f9d05766c0149c1a3be14c634310c4b7719",
        "logIndex": 23,
        "topics": [
          "0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925",
          "0x00000000000000000000000000a14a1d6af3e2944a3e102cf182c784f2331ffd",
          "0x0000000000000000000000006877cf16dd1e7fe141312ea585cf2b7a80e99882"
        ],
        "data": "0x0000000000000000000000000000000000000000000000000de0b6b3a7640001"
      }
    ],
    "status": 1
  },
  "compressedTx": "0x095ea7b3 ( stub: 0000000000000000000000006877cf16dd1e7fe141312ea585cf2b7a80e998820000000000000000000000000000000000000000000000000de0b6b3a7640001 )",
  "gasCost": 54396029802114,
  "gasUsed": 46158,
  "date": "2019-12-20 20:03:49 UTC",
  "ether": 0.000000000000000000
}

Full blocks tx:
    {
      "hash": "0x2fe35e3cec7ee5bba3b1610ccfc8945f684f0fee2915e28deacead39ebb214fb",
      "blockHash": "0x95655a6b802bdc1dd34e4b143e7df48ea789e51242c3efeefca69eaae7193c62",
      "blockNumber": 9137164,
      "transactionIndex": 7,
      "nonce": 2,
      "timestamp": 1629298156,
      "from": "0x00a14a1d6af3e2944a3e102cf182c784f2331ffd",
      "to": "0xd7bb0f9d05766c0149c1a3be14c634310c4b7719",
      "value": 0,
      "gas": 60005,
      "gasPrice": 1178474583,
      "input": "0x095ea7b30000000000000000000000006877cf16dd1e7fe141312ea585cf2b7a80e998820000000000000000000000000000000000000000000000000de0b6b3a7640001",
      "hasToken": 0,
      "receipt": {
        "contractAddress": "0x0",
        "gasUsed": 46158,
        "effectiveGasPrice": 1178474583,
        "logs": [
          {
            "address": "0xd7bb0f9d05766c0149c1a3be14c634310c4b7719",
            "logIndex": 23,
            "topics": [
              "0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925",
              "0x00000000000000000000000000a14a1d6af3e2944a3e102cf182c784f2331ffd",
              "0x0000000000000000000000006877cf16dd1e7fe141312ea585cf2b7a80e99882"
            ],
            "data": "0x0000000000000000000000000000000000000000000000000de0b6b3a7640001"
          }
        ],
        "status": 1
      },
      "gasUsed": 46158
    }

**Comment by tjayrush** [comment]
Just to help me debug this. You can usually add `--raw` to any of the command in `tools` category (`chifra blocks`, `chifra traces` etc.)

`--raw` will return the data as received from the node with no translation at all -- we simply query the node and spit out the result. 

I'm pretty certain that `chifra blocks --raw --fmt json 9137164` will return the same timestamp as `chifra blocks --fmt json 9137164`, but just to be certain, would you mind pasting that below?

**Comment by tjayrush** [comment]
Also, please do these two commands and post the result:

```
chifra when --timestamps 9137164
chifra when --timestamps 1629298156
```

**Comment by davidfsol5** [comment]
$ chifra when --timestamps 9137164
blocknumber     timestamp
9137164 1629298156
$ chifra when --timestamps 1629298156
blocknumber     timestamp
0 workin1629298156

**Comment by davidfsol5** [comment]
This related to Issue #1685?

**Comment by tjayrush** [comment]
I'm pretty sure what you have here is a similar problem to the one you have with names and abi files. That is, our installation assumes the user is using mainnet.

You may have to re-scrape something. I'm not sure how long it will take, but I'd be interested to learn.

If you do `find ~/.local/share/trueblocks/ | grep "ts.bin"` it should return at least two files (possibly more -- ignore any that have `nfts.bin` in them). These are files that contain a map of timestamps to block numbers (you would think you could query this from the chain, but you can't directly -- you have to query the whole block which takes forever. Not sure why that is.) Extracting timestamps speeds up `chifra export` dramatically. `chifra blocks` does not use the timestamp file. `chifra when --timestamps` does use the timestamp file.

The timestamp file gets created during the scrape -- **if it doesn't already exist** -- and this is the problem. The installation installs the timestamp file up to a certain block number -- but those timestamps are from mainnet.

Since you already had the file, your scrape of Rinkeby didn't create it.

**Solution** -- using the above find command to find them, either delete (they're useless for Rinkeby) or save somewhere else the timestamp files. Then, before re-running `make` (which will replace the files) restart your scraper.

I hope -- and I cannot be sure because I've never done this before -- the scraper will see that it has no timestamp and it will 'freshen' it.

If you don't understand, please let me know, and I will try to explain better (in fact, I'll add another comment here with line by line instructions). As you're the first one to scrape Rinkeby, any information you give me will help make it easier on those who follow.

Thanks.

**Comment by tjayrush** [comment]
Instructions for re-scraping ts.bin file.

1. cd into the configuration folder (`~/.local/share/trueblocks` on Linux, `~/Library/Application Support/TrueBlocks` on Mac)
2. Do `find . | grep "ts.bin"` (this should return at least two files -- one at the root of the folder, on in `./unchained/` -- ignore any others).
3. Either delete or move these files
4. Without re-running `make` (which will replace the ts.bin.gz file), run the scraper
5. It should recognize that it's missing the ts.bin and start to re-create it. (Once it's recreated, `make` will no longer copy it).

This should start at block zero and build up the ts.bin one block at a time. It should not take as long as the original scrape, but it may take a while.

When it's done, rerun the above two commands from your original post. They should agree.

**Comment by tjayrush** [comment]
> This related to Issue #1685?

Actually, no, I don't think it is. Your issue is almost certainly the fact that you're running against Rinkeby and we stupidly install timestamps for mainnet.

**Comment by davidfsol5** [comment]
So, a better mental model of the issue is a caching problem. Logically, the cache is missing a dimension (chain) in its primary key. Physically, the cache is in a file store. So, primary key is a path. Something like adding a level path, e.g., ~/.local/share/trueblocks/<chain-name>/... might  be in order?

**Comment by tjayrush** [comment]
Yes. So I've been thinking in `trueBlocks.toml` we could add a value called `chain` or something with values `mainnetEth`, `rinkebyEth`, optimismWhatever`.... (There's an EIP for this called `chain-agnostic-id` we could look at.)

And then all the calculations where we calculate a path to any data (which are all already parameterized and centralized in a single function in the code) would just need a new level added.

You can kind of already do that with the `indexPath` and `cachePath` variables, but that does work for an installations with multiple chains.

Your mental model is exactly right.

**Comment by tjayrush** [comment]
For future reference: h t t p s://github.com/ChainAgnostic/CAIPs/blob/71b68a40f07c0f3435fbcf46a6b503efc3c569d7/CAIPs/caip-2.md

**Comment by davidfsol5** [comment]
I ran 
   $ find ~/.local/share/trueblocks/ | grep "ts.bin"
Got the result
   ~/.local/share/trueblocks/unchained/ts.bin
   ~/.local/share/trueblocks/ts.bin.gz
Moved these two files to ~/tmp.
Tried to rescrape, but I think server is running (ps shows flame and chifra processes). How do I stop the server?

**Comment by tjayrush** [comment]
`ps -ef |  grep chifra` and note the pid. then `kill -9 pid`.

 You can’t really hurt the server because it carries no state.
 
 You may have to delete a file the next time you try to run it, but it will tell you which file.

**Comment by davidfsol5** [comment]
Thanks. Successfully killed server, but scraping just picks up where it left off, and find ~/.local/share/trueblocks/ | grep "ts.bin" still returns nothing.

**Comment by tjayrush** [comment]
It only 'freshens' the timestamp file when it consolidates a chunk, so my guess is that you're close enough to the head that it's not consolidating until it gets 2,000,000 records. Can you tell, when it's done with one 'pass' does it say how many more records it needs?

Also, just since last night, I pushed code that will update the timestamps file every time it's accessed just prior to opening it, so most commands related to time (`chifra when --timestamps`) should cause a re-creation of the `ts.bin` file. You should stop the scraper though. (It should just work with both running at the same time, but let's not test that now.)

**Summary:** Kill the scraper. Run `chifra when --timestamps` and let me know what you see.

Once that's finished, you can run `chifra when --timestamps --check`, which checks the actual blocks against the timestamps stored in the cache, and will hopefully report no errors. (It would have reported errors previously, which makes me think we should suggest to the user that he/she runs some checks after install...)

**Comment by davidfsol5** [comment]
I did a git pull from my trueblocks-core folder, cmake ../src and make from builds. 
$ find ~/.local/share/trueblocks/ | grep "ts.bin" returned ~/.local/share/trueblocks/ts.bin.gz as you said. 
$ chifra when --timestamps spat out a very large number of lines with two values (blocknumber, timestamp). 
Last blocknumber was 12942744, which indicates to me that the "when" command is operating in the context of mainnet. I think that the only source of that context on my computer is  ~/.local/share/trueblocks/ts.bin.gz.
$ chifra when --timestamps --check
57736342 (     26)- <WARNG> : Stored block number (0) is different to block number 8288086.
57745944 (   9602)- <WARNG> : chifra when --timestamps --fix 8288086 # should be 8288086.1616554681
...
58893190 (     10)- <WARNG> : Stored block number (0) is different to block number 8322347.
58918775 (  25585)- <WARNG> : chifra when --timestamps --fix 8322347 # should be 8322347.1617068699

**Comment by davidfsol5** [comment]
I deleted  ~/.local/share/trueblocks/ts.bin.gz and ~/.local/share/trueblocks/unchained/ts.bin.
reran chifra when --timestamps 
only output was the column headers (blocknumber     timestamp)
chifra when --timestamp --check returned an error (Could not open timestamp file. Quitting...)

**Comment by davidfsol5** [comment]
So, I'm thinking that my git pull didn't pick up your push.
$ chifra status --terse
client: erigon/2021.08.4/linux-amd64/go1.16.7 (not archive, tracing)
2021/08/26 09:50:19 trueblocks: GHC-TrueBlocks//0.10.2-alpha-9dca7b41c-20210812 (eskey, no pinkey)
Was it to the develop branch?

Scraping is only 10,234 records shy of consolidation.

**Comment by davidfsol5** [comment]
Got to consolidation. Still no timestamp file recreation.

00048221 (  48221)- <INFO>  : Block scraper is running...

00049235 (   1014)- <INFO>  : ----- Scraping 9183006 of 9183317 (311 from head) ------------------------------
00167723 ( 118488)- <INFO>  :
00167741 (     18)- <INFO>  : Consolidation pass 0
01657550 (1489809)- <INFO>  :   Starting search at record 1999999 of 2020520
01657674 (    124)- <INFO>  :   Break line 2000077 of 2020520. [0 to 2000077 of 2000078]
06900191 (  18073)- <INFO>  :   Extracting addresses...extracting appearances...exporting...finalizing...binary file created ✓
06900693 (    502)- <INFO>  :   Wrote 2000078 records to /home/david/.local/share/trueblocks/unchained/finalized/009162365-009183082.bin
07263850 ( 363157)- <INFO>  :   Wrote 20442 records to /home/david/.local/share/trueblocks/unchained/staging/009183289.txt
07318928 (  55078)- <INFO>  :   ...pass completed.

 find ~/.local/share/trueblocks/ | grep "ts.bin" returns nothing.

**Comment by tjayrush** [comment]
> Was it to the develop branch?

Always to the develop branch.

**Comment by tjayrush** [comment]
Can you kill the scraper, do a fresh pull on develop branch, then `cmake ../src`, `make -j <n>` 

Delete the ts.bin.gz

and then `chifra when --timestamps`.

It should rebuild the timestamps file using Rinkeby.

Are you saying it fails?

By the way -- I'm doing all this because I'm trying to avoid telling you you have to re-start the scrape.

In the worst case, you should be able to remove `~/.local/share/trueblocks/unchained` and it will get re-created along with the timestamp file as long as you don't build between removing and re-starting the scrape.

**Comment by davidfsol5** [comment]
Above export and blocks commands return the same timestamp value now. This issue is is now a non-issue. Thank you, sir. 

Point of order... Should these things be closed by TrueBlocks or the issuer?

**Comment by tjayrush** [comment]
I'll close it now, but you (and anyone else) is more than welcome to close any issue they want. I like closed issues a lot better than open ones.

**Comment by tjayrush** [comment]
Thanks so much for taking the time to help me figure it out.

**Comment by tjayrush** [comment]
I added this issue just to track the problem with the files being replaced on build: https://github.com/TrueBlocks/trueblocks-core/issues/1724
