### ISSUE TITLE
Allow increasing the number of slow queries through config/options

### ISSUE THREAD

**Issue by ivancho** [TrueBlocks/trueblocks-core#1895]
**Context:**
Using chifra in API/serve mode, version "0.15.0-alpha", configured to use a remote RPC (https://mainnet.infura.io)

**Problem:**
When calling `/export?addrs=...` on a new address, we only receive 10 transactions, even when the account has more. On the next call, we receive 20 transactions (previous 10, plus 10 more), then 30, etc

**Possible solution:**
Based on
https://github.com/TrueBlocks/trueblocks-core/blob/4a0bdbcd0b58df0da01693b4046f388eae7684f4/src/apps/acctExport/handle_accounting.cpp#L80
it seems that this is a hard-coded limit. Since a client to the API could be happy to wait for much longer, could we make this more flexible? One solution is to allow dynamically providing this limit per-request, another to make it configurable in the application config. I would be happy to send a PR with whatever solution you agree is best.

**Comment by tjayrush** [comment]
Thanks so much for your report.

I'm curious why '10'. If you had said '250' I would have said that makes sense since the API does limit, but it limits to 250 records not 10. I wonder if Infura is limiting in some way.

Ignoring that for a second, you can use the --first_record / --max_record pair to get pagination. See `chifra export --help` to see options.

If you do (further) `TEST_MODE=true chifra export --help` you'll see a few additional 'hidden' commands. These are commands that we are planning on supporting but that are not yet fully tested. 

Does that help.

**Comment by ivancho** [comment]
I think the 10 comes from the >9 comparison for slowQueries. After the first call, the first 10 txns are cached, so they no longer increment slowQueries in `loadTx_Func`, but the next 10 that need to hit the RPC still do, and that causes `acct_Display` to return false, which breaks the traversal in `libs/acctlib/traverser.cpp` - at least that's my interpretation, I haven't stepped through it in a debugger

**Comment by tjayrush** [comment]
Interesting. What happens if you make that lines say `bool tooSlow = false; // (isApiMode() && opt->slowQueries > 9)` In other words, comment it out.

**Comment by tjayrush** [comment]
Try adding `--cache` to your query. It may not fix the first query (since we call a `slowQuery` any time we hit against the node), but the repeated queries after that for the same block will not only be much faster, but won't increment that counter.

If I understand you above comment, you'd like an optional config file or command line control of that number (10 in this case). Is that right?

I doubt it would be a command line option, but it could easily be a config file item. Let me know if that's what you meant.

**Comment by tjayrush** [comment]
This is done in the next commit. To extend the number of `slow-queries`, edit a file called $CONFIG/acctExport.toml and add an item:

```
[settings]
max_slow_queries = N
```

The default is 13.
