### ISSUE TITLE
Does trueblocks support BSC

### ISSUE THREAD

**Issue by SuchJitter** [TrueBlocks/trueblocks-core#2020]
I'm wondering if Trueblocks supports the Binance Smart Chain, since it essentially is a fork off ethereum.

**Comment by tjayrush** [comment]
We are working on a multi-chain version (for all the commands including `chifra serve` you could add `--chain XXX`.

We're trying very hard to make it agnostic as to which chains it does or does not support. In other words, all you would have to do to get 'support' is properly configure a few things.

For us, the hardest part is getting access to an RPC endpoint that isn't (a) expensive, or (b) rate limited since TrueBlocks hits on the RPC really hard. If you have one, I can work with you to start testing (as I say, the feature is not quite ready). 

Would you be interested in helping us there?

Otherwise, BSC will probably fall behind other chains that are smaller, easier to stand up and run.

**Comment by SuchJitter** [comment]
We are currently syncing one. Will let you know when it is done. Can you tell me some key differences between ethereum and bsc (apart of PoS and PoW)

**Comment by SuchJitter** [comment]
Is there some way I can contact you outside of GH?

**Comment by tjayrush** [comment]
There's a link to our discord here: https://trueblocks.io. DM me is the easiest way.

As far as difference between mainnet and BSC, I don't really know. My feeling is that from the perspective of TrueBlocks and chifra (that is from the perspective of the bits and bytes) there won't be much difference at all. As long as the RPC is compatible (at least the RPC's we need -- and I would be surprised if they weren't) there won't be any difference.

Is that what you meant? In any case, please let's move this to discord. I'll close this issue so it doesn't linger.
