### ISSUE TITLE
geth  'the method trace_block does not exist/is not available'

### ISSUE THREAD

**Issue by ching2018** [TrueBlocks/trueblocks-core#2185]
when i used ```chifra scrape run```, i got ```the method trace_block does not exist/is not available```.

**Comment by tjayrush** [comment]
When you first set up TrueBlocks, you probably configured it to use a particular `rpcProvider` (in the `trueBlocks.toml` file). This RPC has to have the `trace` RPC endpoints enabled. Are you running your own node? If yes, you should be able to restart the node and enable tracing RPCs. 

An easy way to figure this out if this is the problem is to run this command:

```
curl --data '{"method":"trace_block","params":["0x1"],"id":"1","jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST <Your_RPC_Provider_Here>
```

using the same RPC provider you configured.

This command has nothing to do with TrueBlocks -- it's a query directly against your node.

If this returns invalid data, then so will TrueBlocks.

If this command returns valid JSON, then so should TrueBlocks.

Make sure this works first, then we can debug any issue you may be seeing with TrueBlocks.

If this solves your problem, please close this issue. Otherwise, please let me know and we can further debug.

**Comment by ching2018** [comment]
> When you first set up TrueBlocks, you probably configured it to use a particular `rpcProvider` (in the `trueBlocks.toml` file). This RPC has to have the `trace` RPC endpoints enabled. Are you running your own node? If yes, you should be able to restart the node and enable tracing RPCs.
> 
> An easy way to figure this out if this is the problem is to run this command:
> 
> ```
> curl --data '{"method":"trace_block","params":["0x1"],"id":"1","jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST <Your_RPC_Provider_Here>
> ```
> 
> using the same RPC provider you configured.
> 
> This command has nothing to do with TrueBlocks -- it's a query directly against your node.
> 
> If this returns invalid data, then so will TrueBlocks.
> 
> If this command returns valid JSON, then so should TrueBlocks.
> 
> Make sure this works first, then we can debug any issue you may be seeing with TrueBlocks.
> 
> If this solves your problem, please close this issue. Otherwise, please let me know and we can further debug.

thanks

```https://geth.ethereum.org/docs/rpc/server```
How to set it up? Only ```http``` setting parameters

**Comment by FancyRatsDave** [comment]
same problem here: using `geth`

seeing that `parity` supports `trace_block` but not available in `geth`

**Comment by FancyRatsDave** [comment]
Assumed I have to set this in `blockScrape.toml`

```
[requires]
tracing = false
```

**Comment by tjayrush** [comment]
I'm sorry. I don't understand your question.
