### ISSUE TITLE
The index will miss data if ethereum node responds with HTTP error

### ISSUE THREAD

**Issue by artur-jablonski** [TrueBlocks/trueblocks-core#2196]
Perhaps I am wrong, but it looks to me that the scraping process is not handling json-rpc errors correctly which can result in missing data in the index. 

https://github.com/TrueBlocks/trueblocks-core/blob/95beba3cfe555b424da6786a7e1d78a1e71de821/src/apps/chifra/internal/scrape/blaze.go#L63-L75

So on line 70 this will call RPC `trace_block` method, and if that ends in error it will log that on lines 72,73

However it will then proceed further and do very similar thing with call to `eth_getLogs`

https://github.com/TrueBlocks/trueblocks-core/blob/95beba3cfe555b424da6786a7e1d78a1e71de821/src/apps/chifra/internal/scrape/blaze.go#L76-L87

And then it will happily carry on and add the data to address channel

https://github.com/TrueBlocks/trueblocks-core/blob/95beba3cfe555b424da6786a7e1d78a1e71de821/src/apps/chifra/internal/scrape/blaze.go#L90

So if the node returns error for the `trace_block` or `eth_getLogs` calls as it happened to me (HTTP 503 with JSON-RPC -32000 "Unable to complete request at this time) then the scraper will just move on as if there was no data for those calls. This in turn will make the appearance list for such blocks not complete. 

The desired behaviour would be to repeat the rpc calls until success and don't move forward before it happens.

**Comment by tjayrush** [comment]
First, thanks so much for your issue. 

This piece of code (it's called Blaze) is currently very twisted. When you call `chifra scrape`, it calls into Go code which then calls into C++ code which then calls into Blaze. The lines you mention (73 in particular) kill Blaze which causes the C++ code to see that and cleanup the 'partial' scrape. It then 'reruns' this part of the chain.

In other words, even though you correctly point out that Blaze won't finish correctly, the calling code does.

So -- I don't think it's a bug....

------------
Having said all of the above, this code is almost ridiculously convoluted due to multiple revisions.

We are currently about 80% through a complete re-write of the `scraper` code, so all of this confusion into Go, out of C++, and back again will all disappear.

Once that code is ready, all of the scraper will be pure Go code (and hopefully fully concurrent).

Thanks for the careful attention and taking the time to report this issue, but can you close it? I don't think it's actually a bug.

**Comment by artur-jablonski** [comment]
Ah, thx! I didn't expect `log.Fatal` to exit the process. I obviously have no clue about golang. I am happy I was wrong :D. 

https://golangdocs.com/log-package-golang
