### ISSUE TITLE
chifra export incorrect `meta.accountedFor.isContract ` field in export API response

### ISSUE THREAD

**Issue by daoleno** [TrueBlocks/trueblocks-core#2210]
Query transactions by address `0xAB1698E2bc31EbA20fDFaf16Ba94513CA04CDF23` in `sepolia` 
```
http://localhost:8080/export?addrs=0xAB1698E2bc31EbA20fDFaf16Ba94513CA04CDF23&chain=sepolia&maxRecords=1
```
`isContract` is always `false`, but this is a contract. https://sepolia.etherscan.io/address/0xAB1698E2bc31EbA20fDFaf16Ba94513CA04CDF23

```json
{
...
    "meta": {
        "unripe": 1575056,
        "ripe": 1575029,
        "staging": 1575029,
        "finalized": 1568820,
        "client": 1575057,
        "chain": "sepolia",
        "clientId": 11155111,
        "networkId": 11155111,
        "namedFrom": {},
        "unNamedFrom": {
            "0x3000bf6041ad065cecfe37d9f26f79228208a763": 1
        },
        "first_block": 0,
        "last_block": 18446744073709552000,
        "accountedFor": {
            "tags": "",
            "address": "0xab1698e2bc31eba20fdfaf16ba94513ca04cdf23",
            "name": "0xab1698e2bc31eba20fdfaf16ba94513ca04cdf23",
            "symbol": "",
            "source": "",
            "decimals": 0,
            "description": "",
            "isCustom": false,
            "isPrefund": false,
            "isContract": false,
            "isErc20": false,
            "isErc721": false
        }
    }
}
```

**Comment by tjayrush** [comment]
This is a "sort of" bug in the old C++ code. Instead of "fixing it", we've decided to remove the code that generates these incorrect values. Once we move to GoLang, we may be able to reconsider how this works. In the current C++ code, in order to provide this information for every query (which is of questonable worth), we would have to slow down every query even if this data is not needed.

I'm going to close this for now, but if you feel strongly about a use case, we can either re-open this issue or create a new one to add back this functionality in the GoLang code.
