### ISSUE TITLE
chifra scrape better ctrl-c feedback

### ISSUE THREAD

**Issue by dszlachta** [TrueBlocks/trueblocks-core#2228]
The current C++ scraper prints nothing when Ctrl-C is pressed, until the user presses it 3 times (then it shows `got 3 SIGTERM/SIGINTs, forcing shutdown`). I think showing messages for first 2 Ctrl-C presses would improve UX.

**Comment by tjayrush** [comment]
The way the C++ code works is that it 'captures' the Control+C if it's in a loop that's been labeled `lock_section` until it leaves the loop with `unlock_section`. Each iteration of the loop it checks to see if Control+C has been hit, and if it has, it will end the loop gracefully. I agree, it should respond with a message to stderr saying something like, "We will respond to your Control+C in a second, we're busy..."  If it gets three hits, it quits without waiting until its loop is finished.

In the Go code, this does not happen (but it needs to).

This is the function where you can print a message if you want, but hopefully this code will all disappear sooner rather than later. https://github.com/TrueBlocks/trueblocks-core/blob/master/src/libs/utillib/database.cpp#L414
