### ISSUE TITLE
Web3Storage 

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-core#2249]
hello! i'm with the team behind web3.storage and nft.storage. some folks had flagged that trueblocks were looking for solutions to make data available on IPFS. would love to chat if that's still the case! we provide a service layer on top of a scalable implementation of IPFS we wrote (see: https://nft.storage/blog/post/2022-07-06-elastic-ipfs/)

**Comment by tjayrush** [comment]
Can you give me a brief explanation of the differences between web3.storage, nft.storage, and Estuary (if you know anything about that). My use case is about 10 to 12 thousand files. About half of them are 30-40 MB. The other half are probably less than a MB. There are about six to eight new files per day...

**Comment by dchoi27** [comment]
Hi! I'm with the web3.storage team. The explanation below might not have ended up too brief, but hopefully it's helpful.

- Broadly, web3.storage is a platform for devs / users that allows them to interact with their data in a much more flexible way that's not tied to where the data is actually physically stored. It natively uses decentralized data / identity protocols (namely IPFS and [UCAN](https://ucan.xyz/)) to enable user-centric / local-first applications, verifiable storage / workloads, and more, but implemented in a way that allows for performance, reliability, and scale.
- At the center of the web3.storage platform is a hosted storage service that can always be relied on for persistently available storage, and what I'd say provides the best service level of any hosted IPFS storage solution today. This storage service runs on [Elastic IPFS](https://github.com/elastic-ipfs/) (which our team wrote because of the scaling and reliability issues we were seeing ourselves with go-ipfs) and utilizes the Filecoin network for an additional layer of redundancy that provides [verifiable storage](https://filecoin.io/blog/posts/what-sets-us-apart-filecoin-s-proof-system/).
- web3.storage is moving to becoming a paid product (this has come from user feedback - pretty much all serious products want to pay for an SLA, etc.). Initial pricing will likely be around $0.15-0.18 per GB per month, but if this seems high, we can chat to see more about your specific use case (the costs we take on can change depending on your write/read behavior)
- The biggest user of the web3.storage platform is NFT.Storage (85M+ uploads). Our team actually first created NFT.Storage and still runs it, but the NFT.Storage project has [its own mission to provide off-chain NFT storage as a public good](https://nft.storage/blog/post/2022-01-20-decentralizing-nft-storage/) (like an Internet Archive for NFTs, extending the availability of all NFT data beyond just what's on-chain). This future of NFT.Storage will likely utilize a hybrid of the web3.storage platform with smart contracts / a DAO on the [Filecoin Virtual Machine](https://fvm.filecoin.io/)
- All NFT data stored on NFT.Storage will be preserved free, forever, but the data does have to be referenced in an on-chain NFT minting transaction
- Estuary is another service to preserve data on Filecoin and make it available on IPFS, using an architecture based around go-ipfs. It's free! If you want to learn more about them, I can put you into contact with their team

Let me know your thoughts and whether you're interested in checking out web3.storage or NFT.Storage when you're able to. We have a new API / client that I can share!

**Comment by tjayrush** [comment]
Thanks so much for this. Very helpful. I totally understand every word you wrote. I appreciate you taking the time. As I said, I'll come back to you.
