### ISSUE TITLE
chifra scrape on evm-based blockchain get error "Ripe files are not sequential"

### ISSUE THREAD

**Issue by comicola** [TrueBlocks/trueblocks-core#2570]
Im trying to create the index of an evm-based blockchain.

When I run /chifra scrape, I got the following error
`EROR[20-11|15:41:05.347] Ripe files are not sequential (000000002-000000002 ==> 000000004-000000004)`

very appreciate if I get some help

@tjayrush

**Comment by tjayrush** [comment]
Would you be willing to test out our docker version in return for a prompt attention to this issue?

In other words, go here: https://github.com/TrueBlocks/trueblocks-docker and follow the README.

My goal here would be for you to help us understand if the docker version works and more importantly (as we know it works) how easy/hard the README is to follow.

In return for your comments (which you can post either in issues on the docker version or in this issue), I'll do what I need to do to help you get TrueBlocks up and running.

If you're interested, let me know. If not, then I guess I would ask you to provide a lot more information about what you're seeing. Otherwise, I suppose I'll close this issue.

**Comment by joeneldeasis** [comment]
What does this error means? I'm also getting the same error using `trueblocks-core` and `trueblocks-docker`.

Here's the logs from what I get when scraping the `polygon mainnet`. 

```
EROR[26-12|02:22:53.466] Ripe files are not sequential (000000447-000000447 ==> 000000482-000000482)
EROR[26-12|02:23:34.902] Ripe files are not sequential (000000447-000000447 ==> 000000482-000000482)
```

**Comment by comicola** [comment]
> core

I temporary fixed that with some change in the code, but if @tjayrush  have some update, it will be better.

**Comment by joeneldeasis** [comment]
> > core
> 
> I temporary fixed that with some change in the code, but if @tjayrush have some update, it will be better.

@comicola can you share the temporary fix?

**Comment by tjayrush** [comment]
I guess I've sort of lost the chain of this issue. Can you catch me up? Have you seen this? https://github.com/TrueBlocks/trueblocks-core/issues/2091.

Have you tried to docker version?

**Comment by joeneldeasis** [comment]
Hi @tjayrush I have tried both of them and getting the same error. I will try your fix on #2091 , will update once done. Thanks!

**Comment by comicola** [comment]
> > > core
> > 
> > 
> > I temporary fixed that with some change in the code, but if @tjayrush have some update, it will be better.
> 
> @comicola can you share the temporary fix?

@joeneldeasis : allow_missing = true will help.

**Comment by comicola** [comment]
@tjayrush , the empty blocks also create the issue on #2647 , please check.

**Comment by tjayrush** [comment]
We are pushing a PR today, but before we merge it with develop, I wonder if you can test it. It's on this PR: #2653.

Let me know if this fixes the issue, and I will merge the change.

**Comment by tjayrush** [comment]
This has been added to the FAQ and can be found by searching closed issue.
