### ISSUE TITLE
chifra daemon - trustless mode for ipfs.unchainedindex.io

### ISSUE THREAD

**Issue by ghost** [TrueBlocks/trueblocks-core#2632]
Hi,
Ipfs gateway unchainedindex doesn't work properly with requested content type "application/vnd.ipld.raw" and "application/vnd.ipld.car".
Mobile client handles these formats to verify content and hashes locally in trustless way.
[TRUSTLESS_GATEWAY.md#http-request-headers](https://github.com/ipfs/specs/blob/main/http-gateways/TRUSTLESS_GATEWAY.md#http-request-headers)

**Conditions**
Http get request to ipfs.unchainedindex.io
header: Accept: application/vnd.ipld.car

**Expected result**
Response with
header: content-type: application/vnd.ipld.car
and corresponding body format

**Actual result**
Response with
header: content-type: application/octet-stream

**Comment by tjayrush** [comment]
May I please ask you to explain this much better? It's not at all clear to me what this means.

My guess is that I will close this issue fairly quickly unless it's much better explained including clear examples of how to reproduce the problem (I don't even know what the problem is).

Sorry to be a pain in the a$$, but our team is very small and we can't really spend time figuring everything out. To the extent you can help us, the more likely the issue will be resolved.

**Comment by ghost** [comment]
How to reproduce:

Http request to **ipfs.io**.
`~$ curl -H "Accept: application/vnd.ipld.car" https://ipfs.io/ipfs/QmZaQHNgDd3kkfRP4TTWeQebedCmWo5D34eQNxjqEnduN3 -v`
```
> accept: application/vnd.ipld.car
< content-type: application/vnd.ipld.car; version=1
```

Http request to **ipfs.unchainedindex.io**.
`~$ curl -H "Accept: application/vnd.ipld.car" https://ipfs.unchainedindex.io/ipfs/QmZaQHNgDd3kkfRP4TTWeQebedCmWo5D34eQNxjqEnduN3 -v`
```
> accept: application/vnd.ipld.car
< content-type: application/json
```

**Comment by tjayrush** [comment]
This issue has become stale. I don't understand exactly what you mean and I don't have the resources to figure it out right now. I'm going to close this, but if you have time and are so inclined, please re-open it and provide more information. (Or, in the best outcome, please provide a PR to fix it.)

Cheers.
