### ISSUE TITLE
chifra scrape "No new blocks at block" when scrape empty blocks

### ISSUE THREAD

**Issue by comicola** [TrueBlocks/trueblocks-core#2647]
@tjayrush , please help me with this issue.

I think there are some thing not right in "trueblocks-core/src/apps/chifra/internal/scrape/handle_scrape_consolidate.go"

On line 33, you check if there are no ripe files in ripe folder, then you consider "No new blocks" and return in function.

But when I scrape private blockchain, if I scrape thought 2000 **empty blocks**, -> that mean no ripe file created, and the error "No new blocks at block" appear.
The scrapers stuck forever at that empty block, cannot process to next 2000 block because it is waiting for "new block".

Let say I scrape a private chain. It have data from block 1-> 5000. But from 5000 -> 14000 they are empty blocks. And the after 14000 the blocks have the data. -> I stuck forever in block 5000 because scrape always said "No new blocks"

I tried to increase number of block to scrape to 5000, 7000 to get pass the empty blocks, but I hit the limit of the RPC and Cloudflare firewall. Some blockchain do not allow me to scrape 5000 block due to their RPC limitation.

Please help.

Thanks.

**Comment by tjayrush** [comment]
First of all, thank you so much for taking the time to put together this issue.

It's very hard for us, given our very limited resources, to handle private chains, but I'm very interested in this problem as I always thought it might appear for private chains.

My trouble is that I have no way to test against private chains (simply because I do not know how to set one up).

Is there any possibility you can give me access to some private chain somewhere? Without it, the best I can suggest is that we would accept a PR if you can figure out a way to fix the issue.

And please do accept my sincere thanks for writing the issue.

**Comment by comicola** [comment]
> First of all, thank you so much for taking the time to put together this issue.
> 
> It's very hard for us, given our very limited resources, to handle private chains, but I'm very interested in this problem as I always thought it might appear for private chains.
> 
> My trouble is that I have no way to test against private chains (simply because I do not know how to set one up).
> 
> Is there any possibility you can give me access to some private chain somewhere? Without it, the best I can suggest is that we would accept a PR if you can figure out a way to fix the issue.
> 
> And please do accept my sincere thanks for writing the issue.

@tjayrush , I've just sent you detail about the chain that has empty blocks in support channel, your Discord server. Please check!

**Comment by tjayrush** [comment]
I believe this is fixed. I'm closing, but if I'm wrong, please reopen.
