### ISSUE TITLE
chifra other Question on Beacon Chain Issuance over time range for @ethburnbot integration

### ISSUE THREAD

**Issue by corygabrielsen** [TrueBlocks/trueblocks-core#2663]
Hi Thomas, I hope you are well and I love seeing this project alive and well. Amazing vision.

I'm coming back to it because I thought maybe you've made some progress.

My bot [@ethburnbot](https://twitter.com/ethburnbot) has been hibernating for some time now. And as an aside, I hope you recall that it was your blog post on uncle block calculation that got me over a hump originally. That info was hard to find last year (top search on google now is beautifully written Alchemy docs).

Anyway, to integrate the Beacon chain for  [@ethburnbot](https://twitter.com/ethburnbot) I need to query the issuance on the Beacon chain between two timestamps.

This is because I aggregate issuance per hour, calculate projected inflation rate, and tweet a nice image.

With the move from PoW to PoS, I can no longer get away with ignoring Beacon Chain.

Do you have an API for this? If not, if you are willing to make it easy for me, I will timebox and help write some code!

Cheers!

cory.eth

**Comment by corygabrielsen** [comment]
Here is the formula. I would rather collaborate on this with a human than GPT.

![image](https://user-images.githubusercontent.com/3518037/211416550-4c7af2eb-910f-406d-af5d-b2edf16d1591.png)

**Comment by tjayrush** [comment]
Why leave out GPT? It's smarter than us.

While, of course, we run a Beacon chain node (Prysm), we don't do any queries against it. Like you, I've kind of avoided it.

I think my main thought is that we're in the middle of porting our entire code base from C++ to GoLang (we think more contributors will be interested in helping us with GoLang), so that's one of the reasons I've not started adding new features (such as support for Beacon chain).

We have a promise to the Ethereum Foundation as part of our grant to be finished with porting to GoLang by the end of March.

Until then, I probably won't be adding any new endpoints or querying the Beacon chain.

I'm happy to try to figure out what might need to happen though...I'm all ears.

**Comment by corygabrielsen** [comment]
We can use GPT but I like making friends too. 

I heard from Domothy at the Ethereum Foundation that @alextes from ultrasound.money is a domain expert here and implemented this for ultrasound.money.

@alextes posted this on Twitter in reply to me asking for help: https://twitter.com/alextes/status/1613051760150728705?s=46&t=FdmrTJBXFpWrf5AV0BqroA

What's on the agenda after March? Maybe we could start some work then.

**Comment by alextes** [comment]
We already have the API @stoooops I could update it so you can consume it within the day. I'll DM you!

**Comment by tjayrush** [comment]
In the tweets you point to, someone says, "...on the EL side it's just gas used × base fee for every block as you know, on the CL side balances update every epoch so you can just track the deltas..." and then, also, "...if a validator is offline or attesting too late they won't get the full reward and the ETH that they would have otherwise received is just never issued..."

I understand all that, but one thing I never understood is where is that balance recorded. Is the balance change (i.e. the reward) recorded on the EL side or the CL side? If it's the EL side, it should be very easy to add something. If it's the CL side, we'd have to wire up querying the CL, which we've not done yet.

**Comment by tjayrush** [comment]
Hi. I would like to close this as it seems to have gone stale. If not, would you be interested in adding a PR to fix this? We will have to resolve this one day, but my expectation is that it won't be for a while and I'm hoping to close as many issues as I can before the end of March. I'll close it now. Please reopen it if you want to make a PR. Thanks for the discussion in any case.
