### ISSUE TITLE
chifra names -Go port and long running process

### ISSUE THREAD

**Issue by dszlachta** [TrueBlocks/trueblocks-core#2790]
The objective is to add missing/incomplete features to the current implementation of names (e.g. CRUD support) and build long running process pattern that 1. would make multiple calls to `names` faster; 2. could also be used with other commands.

### 1. Support CRUD in Go port
CRUD operations should only be allowed for private names database. We can add "publishing" feature later on.

### 2. Use Unix Domain Sockets to connect to running `chifra daemon`
Unix Domain Socket is lightweight in-memory only socket that doesn't use OS' networking stack. We can use it to communicate with our API server.

We would not start the server automatically if it's not running, yet. In the next iteration, we can use Go-based supervisor to start and control processes. These two projects seem like a good fit:
- https://github.com/canonical/pebble
- https://pkg.go.dev/github.com/thejerf/suture/v4 

### 3. Decide if we should use a database
As mentioned in #2251 we could use a database to store names (both public and private ones). SQLite is a natural candidate being used in C++ codebase. It's relational, doesn't require installing from the user and keeps the whole database in a file. It is possible to import from `.tsv`, so maybe we could distribute names as one file (currently 2 MB) and just load it.

**Comment by dszlachta** [comment]
@tjayrush what do you think?

**Comment by tjayrush** [comment]
I agree completely that only private names can be added/edited. And, if those addresses already exist in our database, the user's edits should be loaded on top of our data. Then, later, we can probably use the unchained index to allow users to publish. We could write a monitor that constantly watches the unchained index and consolidates new published names databases (from a given publisher if the user wishes).

As far as sockets -- I'm totally open to them. I have this early 1990s bias that says they are not easy to use nor are they reliable, but that information is 30 years old, so maybe they're better. It can't be worse. Totally open to exploring it. Did you consider Protocol buffers? I understand that this is something Google uses as a replacement for HTTP. Just curious.

Totally open to the database idea if we remember to consider the "publish" part of all the data we create. We want to publish to IPFS (because it has all those sharing characteristics), but I can easily see how we can do that and also use a database. I don't see us publishing an SQLite database to IPFS, but I guess it's possible.

All steam ahead.

**Comment by dszlachta** [comment]
> As far as sockets -- I'm totally open to them. I have this early 1990s bias that says they are not easy to use nor are they reliable, but that information is 30 years old, so maybe they're better. It can't be worse. Totally open to exploring it. Did you consider Protocol buffers? I understand that this is something Google uses as a replacement for HTTP. Just curious.

Sure, protocol buffers are definitely on the table, but we'd have to define the services, then generate the code and probably find a good place to keep it. So I was thinking to start small with Unix Domain Sockets and then in the next iteration we can switch to protocol buffers. Unix Domain Sockets are special kind of socket, they're kept in kernel memory, so it should be safe to use them.

**Comment by tjayrush** [comment]
I'm going to close this. We can refer to it later if we need it.
