### ISSUE TITLE
chifra cmd - add http proxy setting for etherscan request.

### ISSUE THREAD

**Issue by 32ethers** [TrueBlocks/trueblocks-core#2920]
Network route to etherscan is not stable. So I have to request via http proxy, but I didn't find the setting in ```trueBlocks.toml```. 

Please add a proxy setting for etherscan, or read from environment variable ```HTTP_PROXY, HTTPS_PROXY```

**Comment by dszlachta** [comment]
This could be useful for environments where the user doesn't have control over the OS (and also Docker).
Ref: https://pkg.go.dev/net/http#ProxyFromEnvironment

**Comment by dszlachta** [comment]
Some more details:
In order to support proxies, we'd need to create a new package with a public function returning `http.Client`. This client would be configured to use proxy read from environment variable using `ProxyFromEnvironment` (link in my previous comment). Something along the lines:
```go
package httpClient

var Client http.Client

func init() {
  // set Client to a new `http.Client`
  // read proxy settings and set Transport for Client, just like here:
  // https://stackoverflow.com/a/53202838
}
```

To add proxy configuration to `http.Client`, we would have to create new `http.Transport`. The details on how to set custom transport for `http.Client` are well covered by this SO answer: https://stackoverflow.com/a/53202838

**Comment by tjayrush** [comment]
To the original poster. Do you think, given the above information, you could make a PR? Dawid is busy on work for our Ethereum Foundation grant and I don't have the time either. I'd be happy to merge it (after review) if you were to make a PR.

**Comment by tjayrush** [comment]
We think this can be handled at the operating system level, so closing.
