### ISSUE TITLE
chifra chunks --publish summary of issues

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-core#2927]
## PUBLISHING RELATED (TO SMART CONTRACT)

Issue #2507
- publishing to the unchained index smart contract is very messy
- Should be automated
- I worry about losing money through a bug or bad key management (this could be solved by publishing from an account with zero money but for gas)
- How often should we publish?
- How much would it cost?
- Can we publish sucessfully on a layer 2 (Optimism) and still be decentralized?
- Before publishing we should carefully verify the data being published.

**Comment by dszlachta** [comment]
Here's how I think we could solve automating and security issues:

1. Generate new smart contract wallet, e.g. with Safe (former Gnosis Safe)
2. Set daily spending limit on this wallet to be enough to pay gas for publishing only.

In `chifra` we need a way to store the key that will be used to publish manifest CID to the smart contract (ideally only performed once):
1. Add new (sub)command to add new private key to `keystore` (a feature of go-ethereum). It should probably read private key and a password from user's input (so this step is not automated, but it doesn't have to be). 
2. Use go-ethereum `keystore` to store the private key in a file encrypted by the password

In order to publish, we need to add some new logic to `chifra`, under e.g. `chifra state --send` (this step would be fully automated):
1. Read newly published manifest's CID
1. Read password from environment variable
2. Access keystore using the password and fetch private key (by using functions from go-ethereum)
3. Use go-ethereum’s `ethTypes.SignNewTx` to create new transaction signed with the private key
4. Call `PendingNonceAt` and `SuggestGasPrice` (parameters we need in order to send the transaction)
5. Call client.SendTransaction with the manifest CID

Some docs: 
- keystore https://goethereumbook.org/keystore/
- sending a tx: https://goethereumbook.org/transaction-raw-create/

**Comment by tjayrush** [comment]
This is great. Thanks for putting this together. One suggestion. We already have `chifra chunks manifest --publish`, maybe we can use that instead of `chifra state --send` (or even use `state --send` internally).

**Comment by tjayrush** [comment]
`chifra chunks manifest --publish` pushes all the index chunks and associated bloom filters to IPFS (both locally -- if IPFS daemon is running, and remote -- if there's an API key).

Also, there's an option on `chifra scrape` called `--publish` that also pushes newly created chunks (and blooms) to IPFS.

**Comment by dszlachta** [comment]
> One suggestion. We already have `chifra chunks manifest --publish`, maybe we can use that instead of `chifra state --send` (or even use `state --send` internally).

Sure, it'll make it simpler 👍

**Comment by tjayrush** [comment]
> Here's how I think we could solve automating and security issues:
> 
> 1. Generate new smart contract wallet, e.g. with Safe (former Gnosis Safe)
> 2. Set daily spending limit on this wallet to be enough to pay gas for publishing only.
> 
> In `chifra` we need a way to store the key that will be used to publish manifest CID to the smart contract (ideally only performed once):
> 
> 1. Add new (sub)command to add new private key to `keystore` (a feature of go-ethereum). It should probably read private key and a password from user's input (so this step is not automated, but it doesn't have to be).
> 2. Use go-ethereum `keystore` to store the private key in a file encrypted by the password
> 
> In order to publish, we need to add some new logic to `chifra`, under e.g. `chifra state --send` (this step would be fully automated):
> 
> 1. Read newly published manifest's CID
> 2. Read password from environment variable
> 3. Access keystore using the password and fetch private key (by using functions from go-ethereum)
> 4. Use go-ethereum’s `ethTypes.SignNewTx` to create new transaction signed with the private key
> 5. Call `PendingNonceAt` and `SuggestGasPrice` (parameters we need in order to send the transaction)
> 6. Call client.SendTransaction with the manifest CID
> 
> Some docs:
> 
> * keystore https://goethereumbook.org/keystore/
> * sending a tx: https://goethereumbook.org/transaction-raw-create/

I'm going to try to work on this one today. `chifra state --send` and then, whenever we create a new manifest (`chifra chunks manifest --pin`) we can ask if the user wants to publish (assume No). In the automation case, we can ignore the user input.

**Comment by tjayrush** [comment]
I'm going to close this issue for now. If we need it later, we can re-open.
