### ISSUE TITLE
export contains some extra logs

### ISSUE THREAD

**Issue by 32ethers** [TrueBlocks/trueblocks-core#2949]
Version: chifra version GHC-TrueBlocks//0.64.0-beta
data source: from chifra scrape
commend:  chifra scrape --fmt csv --logs 0x7a58c0be72be218b41c608b7fe7c5bb630736c71 0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef > file.transfer.logs.csv

issue: 
I'm trying to export all transfers of people token on etherium, I filtered by contract address and topic, but the result contains transfer of other token. 
Take a look at tx: 0xf8c514b5e0df0338536b70aa7de85dda4ac8426f9a1f95aedc24889413ca23f5

![图片](https://github.com/TrueBlocks/trueblocks-core/assets/115340054/a989e343-99c1-4c4f-b962-62c9977e5efb)

You can see erc20 transfer of other token in this transaction is also exported. This is confusing and would add extra size to the file.

**Comment by tjayrush** [comment]
I'm pretty sure I understand what's going on here, but please help me figure this out.

My guess is that the display is correct, but it's not quite giving you what you want. When you do

`chifra export <address> --logs` it will give you every log that the given address was ever involved with.

When you add a topic, it will filter that list but only for the topic.

This is what you did. The "extra" logs are coming from other smart contract that generated a log with the given topic and had the given address in it.

What you want (I think) is to add another filter called `--emitter`. This will limit the display to logs in which the given address appears and has the topic you want AND was emitted by the given emitter.

In your case, both `<address>` and `<emitter>` are the same (but they don't have to be). 

You could have, for example, list every log generated by the DAI contract for your address with a topic.

Hope this helps. If I've not explained it will (or if my explanation is incorrect -- that's why I asked you to help me), let me know and I'll dig deeper.

If this answers your question, please close this issue.

**Comment by 32ethers** [comment]
Thank you, I think I should read the document more carefully

**Comment by tjayrush** [comment]
Thanks. This is actually other people have asked about, so the docs probably need improvement. I'll add it to the FAQ.
