### ISSUE TITLE
Allow caller to close errorChan in IterateOverMap

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-core#3027]
In some cases, for example when we're processing things in a `fetchData` loop, we want to IterateOverMap and then later do other things with the results. Because we want all errors to be in the same stream, we use `errorChan` from the `fetchData` function, but `IterateOverMap` closes the error channel. It doesn't need to. This fix pulls the responsibility for closing the error channel to the caller.

**Comment by tjayrush** [comment]
Closing this because the current implementation depends on the error channel being closed to leave the iteration loop. That's not the only way to do it. We could send a sentinel value as we do elsewhere (for example, `Freshen`).

**Comment by dszlachta** [comment]
The rule of thumb is 
> Only the sender should close a channel, never the receiver. Sending on a closed channel will cause a panic. 
(https://go.dev/tour/concurrency/4)

`StreamMany` is an exception, but only because we want to limit the amount of boilerplate code in `fetchData` (and we only close the channels when `fetchData` finishes).

We can easily send any error from `IterateOverMap` to `errorChan` using
```golang
err := <-iterationErrorChan
errorChan <- err
```
or
```golang
errorChan <- (<- iterationErrorChan)
```
(https://stackoverflow.com/questions/35966277/sending-directly-from-one-channel-to-another)
