### ISSUE TITLE
chifra state - Allow following proxy in `chifra state --call`

### ISSUE THREAD

**Issue by dszlachta** [TrueBlocks/trueblocks-core#3173]
As one user (StErMi) pointed out in Discord (https://discord.com/channels/570963863428661248/814482078498029568/1144283200508661771), `chifra state --call` doesn't automatically detect that a contract is a proxy. 

It seems fine at first, because we have `--proxy_for` option, but `chifra state -p proxy`knows that it is a proxy. So we already have logic to detect proxies, but it's not being used by `chifra state --call`.

It looks like it would be easy to add e.g. `--follow` option for `chifra state --call` and it would make life easier when calling proxied contracts.

**Before**
```bash
chifra state --call 'name()' 0x6c3ea9036406852006290770bedfcaba0e23a0e8
# Error: the --call value provided (name()) was not found: abi not found 
```

**After**
```bash
chifra state --call 'name()' 0x6c3ea9036406852006290770bedfcaba0e23a0e8
# Error: the --call value provided (name()) was not found: abi not found 

chifra state --call --follow 'name()' 0x6c3ea9036406852006290770bedfcaba0e23a0e8
# blockNumber	address	signature	encoding	bytes	compressedResult
# 17985361	0xe17b8adf8e46b15f3f9ab4bb9e3b6e31db09126e	name()	0x06fdde03		{val_0:PayPal USD}
#               ^- note the implementation address
```

**Comment by tjayrush** [comment]
In the C++ code it would use an implementation if it could find one automatically. What it would do is (1) call the contract as given on the command line, if that failed, it would (2) try to get the implementation automatically using one of the methods we use in `--proxy_for` and then, if that didn't work, fail.

The `--proxy_for` was only ever intended to be used when the automatic path didn't work (which is sort of frequent because a lot of people make the `implementation` function private (for some unknown reason).

So, instead of adding a new option (`--follow`) just follow automatically if you can and fail with a better message (asking them if they've tried `--proxy_for` for example) if you can't.

**Comment by tjayrush** [comment]
If a call fails, try to find a proxy and if we find one, try to use it, then fail. This used to work in C++, but didn't get ported.

**Comment by tjayrush** [comment]
This already works with `--proxy_for` option
