### ISSUE TITLE
Could not establish ts file: abi not found

### ISSUE THREAD

**Issue by mbwmbw1337** [TrueBlocks/trueblocks-core#3205]
New install across six nodes all same issue showing `EROR[06-09|10:10:30.541] Could not establish ts file: abi not found` but response as expected.

```
  chifra blocks 12
EROR[06-09|10:10:30.541] Could not establish ts file: abi not found
PROG[06-09|10:10:30.543] [..................................................]100%     1/    1 
{
  "data": [
    {
      "baseFeePerGas": 0,
      "blockNumber": 12,
      "date": "2015-07-30 15:29:04 UTC",
      "difficulty": 17179844608,
      "gasLimit": 5000,
      "gasUsed": 0,
      "hash": "0xc63f666315fa1eae17e354fab532aeeecf549be93e358737d0648f50d57083a0",
      "miner": "0x0193d941b50d91be6567c7ee1c0fe7af498b4137",
      "parentHash": "0x3f5e756c3efcb93099361b7ddd0dabfeaa592439437c1c836e443ccb81e93242",
      "timestamp": 1438270144,
      "transactions": [],
      "uncles": []
    }
  ]
}
```

**Comment by tjayrush** [comment]
How did you install Trueblocks? Using `make`?

Also, can you send the results of `chifra status` (may not work).

If that doesn't work, please connect with us in discord. We can DM some debugging...

It feels like your installation isn't quite right.

**Comment by mbwmbw1337** [comment]
Hi @tjayrush thank you for the quick response!

Yes, via make. I will jump on Discord shortly. I am using erigon would that have any impact?

```
$ chifra status
EROR[06-09|20:04:55.017] Could not establish ts file: abi not found 
06-09|20:04:55.086 Client:            erigon/2.49.0/linux-amd64/go1.20.7 (archive, tracing)
06-09|20:04:55.086 TrueBlocks:        GHC-TrueBlocks//1.0.0-release (eskey, no pinkey)
06-09|20:04:55.086 RPC Provider:      http://localhost:9800 - mainnet (1/1)
06-09|20:04:55.086 Root Config Path:  /home/erigon/.local/share/trueblocks/
06-09|20:04:55.086 Chain Config Path: /home/erigon/.local/share/trueblocks/config/mainnet/
06-09|20:04:55.086 Cache Path:        /home/erigon/.local/share/trueblocks/cache/mainnet/
06-09|20:04:55.086 Index Path:        /home/erigon/.local/share/trueblocks/unchained/mainnet/
06-09|20:04:55.086 Progress:          0, 0, 0, 0 ts: 0
```

**Comment by tjayrush** [comment]
What exactly do you mean when you say, "new install across six nodes"? 

One thing I'm seeing is thattar (a) it does seem to be connecting to Erigon (the first line of the `chifra status` report), but the last line is reporting that Erigon thinks the head of the chain is zero (which means Erigon is not fully synced).

If Erigon is not fully synced, we won't be able to find the timestamps database (since we read the Unchained Index smart contract in order to find that data on IPFS).

The last line shows five numbers: headOfChain (as reported by Erigon), finalized, staging, unripe, and latest timestamp (the `ts:` part). Finalized is our latest consolidate chunk. Staging is around 28 blocks behind the chain head, unripe is about two blocks behind chain head.

So, all of those numbers makes sense to me if Erigon is still syncing.

What do Erigon's logs say? Stage 5/12? 7/12?

If Erigon is fully synced, you should be able to query directly using `curl` with `eth_getBlockByNumber` for any block and get valid data.

**Comment by tjayrush** [comment]
Is this still a problem? Does the last line of `chifra status` report any value for the first number? Until yes, I think Erigon is still syncing. Given no response, I'll close this. If it's still a problem please let me know and we can debug further.
