### ISSUE TITLE
Indexing an unsupported EVM chain

### ISSUE THREAD

**Issue by RilRil** [TrueBlocks/trueblocks-core#3229]
Hi, I'm trying to index our chain (Chiliz Chain) which is a fork of BSC (using Geth). I'm running a full archive node locally.
here is my trueBlocks.toml 
```
[chains.mainnet]
apiProvider = "http://localhost:8080"
chainId = "88888"
localExplorer = "http://localhost:1234"
remoteExplorer = "https://scan.chiliz.com"
rpcProvider = "http://localhost:8545"
symbol = "ETH"
```
I've tried several time to delete everything and rebuild but somehow I get random results. now im getting this when running `chifra status`
![Screenshot 2023-09-21 at 16 39 28](https://github.com/TrueBlocks/trueblocks-core/assets/386207/f530839e-f3b0-4668-8767-c9aa50b720a6)
but I got this earlier :
![Screenshot 2023-09-21 at 16 08 15](https://github.com/TrueBlocks/trueblocks-core/assets/386207/e6ac981c-1d24-44b2-bd8d-653e1240bf73)

and when running `chifra scrape`:
![Screenshot 2023-09-21 at 16 40 58](https://github.com/TrueBlocks/trueblocks-core/assets/386207/1892d773-2b8d-4f68-bc6c-a3e11733c2f7)

Can someone help debugging this ? thanks in advance !

**Comment by tjayrush** [comment]
We're working on a number of improvements to the scraper, including making this issue (scraping chains that are not included in the default set of known chains) easier. This is the list of chains that we currently (but not officially support) know about: https://github.com/TrueBlocks/trueblocks-core/blob/fix/fix-scraper-5/src/other/install/trueBlocks.toml#L26.

We support Ethereum Mainnet, Ethereum Sepolia, and Optimism.

I've marked this issue with the `TC-apps:scrape` label which means it will be addressed before we close the next release which includes a lot of other fixes for scraping. 

Please stay tuned. Look for an announcement of the release.

When you see this issue close, you'll know we addressed it in the branch.

This work is on branch `fix/fix-scraper-5` currently, if you want to be adventurous, but note that we promise nothing on this branch. We may (and probably will) break things as we proceed to release.

**Comment by tjayrush** [comment]
I'm going to close this issue because we've implemented better error messaging when any of a number of things happen:

1) The user supplies a `--chain` that isn't configured -- they get a message saying the chain configuration was not found,
2) The chain was found in the configuration file, but no Unchained Index database record was found either because:
   a) the record does not exist, or
   b) the record exists but not with the supplied `--publisher` (or the default preferred publisher), or
3) The RPC endpoint the user is running against does not support tracing, or 
4) The timestamp or index portions are reported by the Unchained Index, but they are not pinned.

In any of these three cases, `chifra init`, `chifra scrape`, `chifra list`, `chifra export` and `chifra chunks` will not work properly.
