### ISSUE TITLE
Additional `export` command examples

### ISSUE THREAD

**Issue by mikeghen** [TrueBlocks/trueblocks-core#3301]
Here are some additional export command examples I think would be helpful in the docs:

1. All mints from a token, would appear as inbound transfers from `address(0)`
2. All swaps on Uniswap for a specific token (Through the UniswapV2 router for example)
3. All internal Ethereum transfers

**Comment by tjayrush** [comment]
Thanks Mike. This is super helpful. I can add these to the website, under the blog, but before I do...help me with something...

I hired someone to write the website, so I don't know everything about it.

As you looked at our website, where did you find any existing example (if you found any at all on the website).

If you didn't find any existing examples on the website, where did you find them.

The reason I'm asking is because I'm looking for the most likely place to put new examples to make it easier for people.

**Comment by tjayrush** [comment]
Copying text here and closing.

https://github.com/TrueBlocks/trueblocks-docs#115
