### ISSUE TITLE
chifra daemon - invalid net_version result "0x1"

### ISSUE THREAD

**Issue by Yiin** [TrueBlocks/trueblocks-core#3467]
$ chifra daemon
INFO[26-12|06:58:12.248] Server URL:         localhost:8080
INFO[26-12|06:58:12.248] RPC Provider:       https://eth.merkle.io
INFO[26-12|06:58:12.248] Root Config Path:   /home/user/.local/share/trueblocks/
INFO[26-12|06:58:12.248] Chain Config Path:  /home/user/.local/share/trueblocks/config/mainnet/
INFO[26-12|06:58:12.249] Cache Path:         /home/user/.local/share/trueblocks/cache/mainnet/
INFO[26-12|06:58:12.249] Index Path:         /home/user/.local/share/trueblocks/unchained/mainnet/
INFO[26-12|06:58:12.471] Progress: Could not load RPC provider: invalid net_version result "0x1"

**Comment by tjayrush** [comment]
I'm going to close this, but if you'd like to re-open it, please do.

In order to proceed, I'm going to need more information. In particular, the result of doing this:

```
TB_DEBUG_CURL=true chifra status --diagnose
```

The first line should show a `curl` command. Running that `curl` command will eliminate TrueBlocks from the equation, so we can see if the problem is TrueBlocks or your RPC connection.

Return just the output of the command (after removing any private info) and post it here, so I can figure out how to proceed.

Cheers.
