### ISSUE TITLE
Remove go.work (and go.work.sum) files from repo. 

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-core#3600]
When I create a brand new GitHub repo and select the GoLang .gitignore, the default exclusions include go.work.

According to ChatGPT, this is standard industry practice.

We should add this file (if present) to our .gitignore and remove it from our own local repos and the remote repo.

**Comment by dszlachta** [comment]
It seems to be more complicated: https://github.com/golang/go/issues/53502
However the Go team seems to lean to "don't check it in" option.
We only have `go.work` because of VS Code complaining. It might be worth checking if we still need it.
If we do, one suggestion in the linked issue was to have a script that creates this file.

**Comment by tjayrush** [comment]
We do need it. VS Code reports errors if it's removed. Those errors go away if the go.work is replaced. I like the idea of a script, especially as I add more and more examples, but when would it run?

**Comment by tjayrush** [comment]
Done.
