### ISSUE TITLE
Bug that needs some more info

### ISSUE THREAD

**Issue by dreaded369** [TrueBlocks/trueblocks-core#3607]
I've gotten this error a few times:

INFO[23-04|04:41:02.364] pulsechain #4781625, found 797771 apps and 564124 addrs (1.4 apps/addr). created 1 chunks, staged 423233 apps (21.2%), need 1576767.
EROR[23-04|04:46:48.666] error at block 4782256: 524 : 52483621 of 20186724 (15403103 blocks from head)
EROR[23-04|04:46:48.701] encountered errors while scraping 
INFO[23-04|04:49:21.735] pulsechain #4783625, found 827622 apps and 594134 addrs (1.4 apps/addr). created 0 chunks, staged 1250855 apps (62.5%), need 749145.

It would be helpful if some more info was given - 
Was it an error that was recovered from (because the next scrape was successfull?)
If it didn't retry and succeed - 
  Will it be retried? 
  Was it added to a list somewhere that can be checked? 
  Is any other action needed/possible?

**Comment by tjayrush** [comment]
In answer to this:

> If it didn't retry and succeed - will it be retried?

the answer is "yes." The scraper will not proceed unless it gets all blocks in the range without error. If it encounters an error anywhere in the current range, it will sleep a bit and then start again at the same range next time. We've seen it repeat for hours before the RPC endpoint comes back up.

This is by design.

**Comment by tjayrush** [comment]
I agree that "EROR[23-04|04:46:48.701] encountered errors while scraping" is not a very helpful error message.

At the very least, we should report the actual error.

**Comment by tjayrush** [comment]
Just clearing something up here. Part of the problem with the error messaging above is that there are "printing artifacts". This happens when we print a "progress line" that returns a string with an ending `\r` and no new line. The error message then follows on but does not clean up to the end of the line. So, for example, this error message is such a case:

```
EROR[23-04|04:46:48.666] error at block 4782256: |||| 524 : 52483621 of 20186724 (15403103 blocks from head)
```

I inserted `||||` where the error message ends and the printing artifact (from the progress message) begins.

The error message is formatted as `"error at block %d: %v", blockNumber, error)`, so we can see that there was an error but it seems to have been empty.

I don't yet know why that happens, but this explain a little bit about why it's more confusing than it should be.

**Comment by dreaded369** [comment]
> I don't yet know why that happens, but this explain a little bit about why it's more confusing than it should be.

What are the chances that some data was missed?

**Comment by tjayrush** [comment]
I'm fairly confident that no data was missed. It won't proceed (ignoring the bad error messaging) if it didn't complete all the blocks in the range without error.

We tried very, very hard as we were building this make sure that was true. We repeatedly re-ran the indexing from scratch and forced it to fail (by overloading the RPC server for example or cutting off the network access).

Of course, I can't say it's perfect, but we tried really hard to make it robust.

One of the reasons for this is because the data is immutable. We should (and do) get identical results from all servers and for all time.

Are you finding errors? If not, perhaps you'll close this issue?

**Comment by dreaded369** [comment]
> Are you finding errors? If not, perhaps you'll close this issue?

I have got an archive node yet so I'm still in the process of scraping from a remote node - still a way to go. 4TB drive arrives tomorrow, so maybe in a week I'll be able to run Trueblocks in a timely manner.  Re. the errors - I just didn't know how seriously to take it. Once I can run it all locally I'll just rerun it and compare files to check.

**Comment by tjayrush** [comment]
Error messaging has always been a bit of a weak point. The code builds the index and keeps re-trying until it gets through without errors. (Same with `chifra init` by the way.) Let me know what you find. If you wish, please close this issue. We can always re-open it.
